name: .NET build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-x64:
    strategy:
      matrix:
        rid: [linux-x64, osx-x64, win-x64]
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      # GITHUB_WORKSPACE : the default location of your repository when using the checkout action.
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      id: build
      run: |
        RELEASE_DIR="${RUNNER_TEMP}/release"
        echo "Release dir: ${RELEASE_DIR}"
        mkdir -v "${RELEASE_DIR}"
        echo "::set-output name=release-dir::${RELEASE_DIR}"
        cd "${GITHUB_WORKSPACE}/KSPModDevInstaller"
        dotnet publish -c Release -r ${{ matrix.rid }} --self-contained false
        cp -v -R "${GITHUB_WORKSPACE}/KSPModDevInstaller/bin/Release/net6.0/." "${RELEASE_DIR}"
        cd "${RELEASE_DIR}"
        zip -r -j "KSPDevModInstaller-${{ matrix.rid }}.zip" "${{ matrix.rid }}/publish/"
      
    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.build.outputs.release-dir }}/KSPDevModInstaller-${{ matrix.rid }}.zip

